# Generated by Django 4.2.2 on 2023-06-28 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Figura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('altura', models.IntegerField()),
                ('valor', models.IntegerField()),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
    ]
